# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger_name', models.CharField(max_length=64)),
                ('blogger_link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=128)),
                ('planet_directory_name', models.CharField(max_length=64)),
            ],
        ),
    ]
